name: buf-push
on:
  push:
    branches:
      - main

# from https://docs.buf.build/ci-cd/github-actions#buf-push
jobs:
  buf-release:
    # Check repository owner so that we don't run on a fork.
    if: github.repository_owner == 'berty'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      # @TODO(gfanton): enable this ?
      # - uses: bufbuild/buf-lint-action@v1
      # - uses: bufbuild/buf-breaking-action@v1
      #   with:
      #     # The 'main' branch of the GitHub repository that defines the module.
      #     against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1"
      - uses: bufbuild/buf-push-action@v1
        with:
          input: "api/protocol"
          buf_token: ${{ secrets.BUF_TOKEN }}
